GET http://localhost:3001/api/blogs HTTP/1.1
Content-Type: application/json
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6InRlcHBvLnRlc3RpQHN1b21pLmZpIiwiaWQiOiI2MWRhYWU5MDllYmNlNzJiYTM4MjIyMmQiLCJpYXQiOjE2NDE3MjE1MzR9.O73GbIkzJQ_YIrpw_CZ32BHF03vJhUDxpqeBBcGt3x4
